run_all.sh
Now checks for gcc version and exits if not supported
=> Fixed run_all.sh 

README.md, configs/README.md, deploy/README.md, deploy/coreboot-rom/README.md, deploy/mixed-firmware/README.md, keys/README.md, operating-system/README.md, operating-system/debian/README.md, operating-system/debian/docker/README.md, stboot/README.md, stboot/data/README.md, stboot/include/README.md, stconfig/README.md
=> Several cleanups

run.config
1G is not enough to fit the rootfs of a default Debian, as it's being
built by us. 2G leaves 371M free space to play with.
=> give qemu 2G RAM

run.sh, scripts/checks.sh, scripts/start_qemu_mixed-firmware.sh
Check for swtpm 0.2.0 and make it mandatory.
Use it to start the mixed firmware qemu bundle.
Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
=> scripts: Make swtpm mandatory

stboot/make_kernel.sh
Rebuild kernel if EFI stub is to be build and initramfs is newer than
the kernel.
Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>
=> make_kernel: Fix dependency tracking

operating-system/common/build_tboot.sh, scripts/checks.sh
gcc9 introduces a new flag "address-of-packed-member", which causes an error
during the build of tboot. To support newer gcc the flag
"-Wno-error=address-of-packed-member"  is included on all concerned gcc
versions.
Tested on:
- gcc (Ubuntu 8.4.0-4ubuntu1) 8.4.0
- gcc (Ubuntu 9.3.0-18ubuntu1) 9.3.0
- gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
=> Support newer GCC versions

stboot-installation/mbr-bootloader/build_image.sh, stboot-installation/mbr-bootloader/fetch_syslinux.sh, stboot-installation/mbr-bootloader/make_mbr_bootloader.sh
This commit fixes the MBR bootloader build.
build_boot_filesystem.sh needs the syslinux fetch, which is is done
in build_image.sh. Therefor make_mbr_bootloader does not work on a
clean repository. This commit creates a separate script for fetching
syslinux and is called in make_mbr_bootloade.sh to call it before
bould_boot_filesystem.sh.
=> stboot-installation/mbr-bootloader: Add fetch_syslinux.sh

stboot-installation/common/build_data_filesystem.sh
The build_data_filesystem.sh script fail, if the path
'out/os-packages/' does not exist. add mkdir command to avoid this
issue.
=> stboot-installation/common: add mkdir for os_pgk_dir

README.md, operating-system/common/get_acms.sh, scripts/checks.sh, scripts/create_and_sign_os_package.sh, scripts/make_toolchain.sh, stboot-installation/common/build_initramfs.sh
Instead of using global GOPATH, create an own gopath in cache/go.
In addition use the git commit to fetch u-root and checkout the remote branch to avoid errors when the local branch diverges, due to a remote rebase.
=> Use isolated gopath in cache/go

stboot-installation/common/build_host_config.sh
Reason: /dev/random might block
Rationale: /dev/urandom use the same CSPRNG as /dev/random.
=> use /dev/urandom instead of /dev/random

Makefile
The GO111MODULE environment variable was removed, which broke the
build. Let us re-add it.
Fixes: 88149e54498b ("Makefile: export all variable")
Signed-off-by: Björn Töpel <bjorn@mullvad.net>
=> build: Re-add GO111MODULE

Makefile, modules/go.mk, operating-system/Makefile.inc, operating-system/debos/Makefile.inc, stboot-installation/common/build_initramfs.sh
Ignore more compile flags on gcc11 for compiling tboot.
=> fix gcc11 (Fedora 34)

.github/workflows/testing.yml, stboot-installation/common/Makefile.inc
only build and sign example os-package, if ST_BOOT_MODE is local.
Relates to issue #97
=> Prevent os-package build on network bootmode

Makefile, modules/check.mk, modules/linux.mk, modules/swtpm.mk, scripts/start_qemu_efi_application.sh, scripts/start_qemu_mbr_bootloader.sh, stboot-installation/efi-application/Makefile.inc, stboot-installation/mbr-bootloader/Makefile.inc
To test the image in runtime it is necessary to install swtpm.
This PR adds recipes to build swtpm inside the repository instead of listing it as a dependency.
=> Build Software TPM Emulator to test images with Qemu

.github/workflows/testing.yml, contrib/default.config, scripts/deps.sh
u-root requires Go version >= 1.15:
ref: https://github.com/u-root/u-root#usage
stboot requires Go version >= 1.16:
commit: 35b5fcf
=> Fix stboot regression and set Go 1.16 as minimum requirement

Taskfile.yml
In the taskfile, "test -f" is used, which makes it impossible to use bash process substitution. Change to "test -e" instead.
=> Less strict "file exist"-check.

README.md, scripts/security_config.sh
Correct the README and the scripts/security_config.sh to use the
correct security_configuration.json field "min_valid_sigs_required",
instead of "minimal_signatures_match".
Signed-off-by: Björn Töpel <bjorn@mullvad.net>
=> Use correct field for minimum number of signatures.

scripts/efi_boot_partition.sh, scripts/efi_image.sh, scripts/mbr_boot_partition.sh
Currently the vfat partion that hosts the LinuxBoot kernel and more,
had a fix size of 12M. This change dynamically adjust the size based
on the actual size of the files.
Signed-off-by: Björn Töpel <bjorn@mullvad.net>
=> Size the vfat partition based on input files.

README.md
Remove the CIDR notation from "gateway", which does not work. Add
"network_interface". Make sure the formatting is consistent.
Signed-off-by: Björn Töpel <bjorn@mullvad.net>
=> README: Correct the example host_configuration.json

.envrc, Taskfile.yml, tasks/go.yml
Enable go modules globally.
If possible, use go modules to install go binaries. (go:install)
However, u-root does not support modules at runtime and requires each
package inside GOPATH. Use go:get and go:checkout to get relevant
packages.
This commit also fixes concurrency issues while fetching multiple
packages at once.
=> task/go: restructure go targets

.github/workflows/testing.yml, README.md, setup.env, tasks/demo.yml, tasks/go.yml, tasks/stboot.yml
Move .envrc to setup.env and make it optional.
It is not required to source the environment file to build
all task targets.
=> Remove .envrc requirement

contrib/default.config, tasks/go.yml
The ability to set version of u-root and stboot was removed in 6383e89
to prevent incompatibility due to API changes. Reintroduce the
configuration options to set the version of all version pinned tools.
=> Reintroduce version configuration

Taskfile.yml, tasks/go.yml
Add target to fetch build dependencies. In this way it is possible to
build installation targets without network access.
=> task: Introduce fetch target

README.md
Default gateway should not be expressed with CIDR notation.  It is an IP
address, see example configuration as well as stboot/opts/hostcfg.go#L70.
=> Fix default gateway documentation

contrib/debos/scripts/pack.sh
Issues like a missing `cpio` binary would go unnoticed in the pipeline.
Lets make theme explicit.
Signed-off-by: Morten Linderud <morten.linderud@mullvad.net>
=> pack.sh: set pipefail to catch errors

tasks/go.yml
Allows us to supply LDFLAGS into the go install command. This is practical to build binaries with embedded versions or other variables.
Signed-off-by: Morten Linderud <morten.linderud@mullvad.net>
=> go: Implement support for GO_LDFLAGS

tasks/go.yml, tasks/stboot.yml
This unbreaks building with go versions higher than 1.15 or so.
The `-uroot-source` command line argument is needed in modern u-root, see u-root/README.
=> bump u-root to v0.10.0

.github/workflows/testing.yml
1.19.1 was picked because Debian bullseye-backports have that version.
Keeping the ubuntu-18.04 on go1.17 to catch (some) breakage on 1.17.
=> Test using go1.19.1 on ubuntu-20.04
