README.md

fixed structure of paragraphes etc.

---

.gitignore
README.md
stboot/install-u-root.sh
stboot/make_initramfs.sh
stconfig/install_stconfig.sh

Add and edit of install_stconfig

---

README.md
stconfig/install_stconfig.sh
testitems/manifest.json

Edit readme again

---

doc/Makefile
doc/st-map.gv

LMK if I should add a generated PNG or something too.

add graph describing where various files go

---

run.sh
scripts/make_toolchain.sh
stboot/mixed-firmware/make_image.sh
stboot/mixed-firmware/make_kernel.sh

Let's include the ugly sudo fix for now and discuss a better solution later tonight.

Build fixes

---

README.md
scripts/checks.sh
stboot/mixed-firmware/make_image.sh

Remove sudo

---

stboot/mixed-firmware/make_image.sh
stboot/uefi-firmware/create_image.sh

Don't ask the user for confirmation, just do it.
Signed-off-by: Patrick Rudolph <patrick.rudolph@9elements.com>

stboot/*/make_image: Use -s when calling parted

---

operating-system/ubuntu18/docker/Dockerfile
operating-system/ubuntu20/docker/Dockerfile
operating-system/ubuntu20/make_ubuntu.sh
scripts/make_global_config.sh

Add run.config relevant environment vars to make_global_config

---

operating-system/ubuntu20/docker/debos.yaml
operating-system/ubuntu20/docker/overlays/netplan/01-ens3.yaml
operating-system/ubuntu20/docker/run-in-chroot.sh
operating-system/ubuntu20/make_ubuntu.sh

Fix Ubuntu20 build

---

operating-system/ubuntu/Ubuntu20.yaml

fix Issue #43

---

operating-system/build_tboot.sh
operating-system/get_acms.sh
stboot-installation/build_kernel.sh
stboot-installation/mbr-bootloader/build_image.sh

Fix tboot directory issue

---

operating-system/ubuntu/Ubuntu18.yaml
operating-system/ubuntu/debos-overlays/etc/apt/sources.list
operating-system/ubuntu/debos_update_ubuntu.sh

Update ubuntu18 to latest version

---

.github/workflows/testing.yml

Add Testing GitHub action workflow.

Testing GitHub action workflow

---

Taskfile.yml
scripts/qemu_run.sh

* task: run qemu targets interactive
* qemu_run.sh: generate swtpm configuration

Fix run target installation

---

.github/workflows/scripts/test-qemu.sh
.github/workflows/testing.yml
Taskfile.yml
modules/linux.mk
tasks/demo.yml

In addition:
* Check if ospkg dir is empty
* add `[ERROR]`  prefix in preconditions

Fix Qemu runtime test workflow

---

.github/workflows/testing.yml
tasks/demo.yml
tasks/linux.yml

build ubuntu debos OS in cache to prevent rebuild
after clean.

Build example-os in cache

---

README.md
Taskfile.yml
contrib/default.config
tasks/linux.yml
tasks/stboot.yml

* Support setting the path #165
* Fix ST_LINUXBOOT_CMDLINE regression due to native task migration #166
* Update README.md documentation and remove obsolete information

Fix regressions / Update readme documentation

---

contrib/default.config
tasks/go.yml

Using stboot commit 4b208b7 introduces optimizations in parsing
of host configuration, security configuration etc. Further the
command line of stboot changed regarding logging.
Signed-off-by: Jens Drenhaus <jens.drenhaus@9elements.com>

Update stboot version.

---

tasks/go.yml

fix #175 and unpin task version.

Fix fetch target

---

README.md

Signed-off-by: Morten Linderud <morten.linderud@mullvad.net>

README: include `demo:server`
